[package]
name = "rtld"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
object = "0.31"
zelf = "0.1"
thiserror = "1"
